name: 'Install Terraform'
description: 'An action to install Terraform on a GitHub runner'
author: 'Prabhat Raghav <prabhat_raghav@outlook.com>'
runs:
  using: 'composite'
  steps:
    - name: Install Terraform
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gnupg software-properties-common
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install -y terraform
      shell: bash  

    - name: Verify Terraform installation
      run: |
        sudo terraform --version
      shell: bash  
