name: 'Install Docker Engine'
description: 'An action to install Docker Engine on a GitHub runner'
author: 'Prabhat Raghav <prabhat_raghav@outlook.com>'
inputs:
  docker_version:
    description: 'The version of Docker to install'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker repository
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install ca-certificates curl -y
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker Engine
      shell: bash
      run: |
        sudo apt-get update
        if [ "${{ inputs.docker_version }}" = "latest" ]; then
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        else
          sudo apt-get install -y docker-ce=${{ inputs.docker_version }} docker-ce-cli=${{ inputs.docker_version }} containerd.io docker-buildx-plugin docker-compose-plugin
        fi

    - name: Verify Docker installation
      shell: bash
      run: |
        sudo docker --version
